version: '3.8'

services:
  app:
    build: .
    container_name: aiohttp
    restart: "always"
    environment:
      aiohttp_app: run.py
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    environment:
        - ALLOW_EMPTY_PASSWORD=yes

volumes:
  redis-data:
  redis-conf: